// src/components/Header.tsx
import React from 'react';
import Kerstmuts from '../assets/kerstmuts.png'; 

interface HeaderProps {
    isChristmasThemeEnabled: boolean;
}

const Header: React.FC<HeaderProps> = ({ isChristmasThemeEnabled }) => {
    
  const ErContent = isChristmasThemeEnabled ? (
    <span className="relative inline-block">
      r
      <span 
        className="absolute"
        style={{ 
          top: '-35px', 
          right: '-35px', 
          width: '60px',    
          height: '60px',   
          transform: 'rotate(15deg)', 
          zIndex: 20, 
        }}
      >
        <img 
            src={Kerstmuts} 
            alt="Kerstmuts" 
            className="w-full h-full object-contain"
        />
      </span>
    </span>
  ) : (
    <span className="inline-block">r</span>
  );

  return (
    <header className="text-center py-8">
      <h1 className="text-5xl md:text-6xl font-bold text-purple-900 tracking-tighter">
        kwartvoorbi.e
        {ErContent}
      </h1>
      <p className="text-purple-700 mt-2 text-lg">Het is bijna tijd voor de borrel!</p>
    </header>
  );
};

export default Header;

// src/components/Header.vue
<script setup lang="ts">
import Kerstmuts from '../assets/kerstmuts.png'

defineProps<{
  isChristmasThemeEnabled: boolean
}>()
</script>

<template>
  <header class="text-center py-8">
    <h1 class="text-5xl md:text-6xl font-bold text-purple-900 tracking-tighter">
      kwartvoorbi.e
      <span v-if="isChristmasThemeEnabled" class="relative inline-block">
        r
        <span 
          class="absolute"
          style="top: -35px; right: -35px; width: 60px; height: 60px; transform: rotate(15deg); z-index: 20;"
        >
          <img :src="Kerstmuts" alt="Kerstmuts" class="w-full h-full object-contain" />
        </span>
      </span>
      <span v-else class="inline-block">r</span>
    </h1>
    <p class="text-purple-700 mt-2 text-lg">Het is bijna tijd voor de borrel!</p>
  </header>
</template>
